"use server";

// ---------------------------------------------------------------------------
// sequenceVideoSplitValidate.ts — SEQGEN.SPLIT.1
//
// Lot D — Validate Split Plan: the ONLY transition to "validated". Split
// from the former `src/actions/sequenceVideoSplit.ts` by IND.SPLIT.1 — see
// `src/actions/sequenceVideoSplitDetection.ts`,
// `src/actions/sequenceVideoSplitCleanup.ts`, and
// `src/actions/sequenceVideoSplitSegments.ts` for the rest.
// ---------------------------------------------------------------------------

import { db } from "@/db";
import { sequenceVideoSplitRuns, sequenceVideoSplitSegments, shots } from "@/db/schema";
import { eq, asc } from "drizzle-orm";
import { deleteSegmentThumbnail, parseFrameRateModeFromParamsJson } from "@/lib/sequenceVideoSplit/detectVideoSplits";
import { roundBoundarySeconds, isReliableFps } from "@/lib/sequenceVideoSplit/frameTime";
import { errRedirectTo, okRedirectTo } from "@/lib/sequenceVideoSplit/actionHelpers";

export async function validateSplitPlan(formData: FormData): Promise<void> {
  const runId = parseInt(formData.get("runId") as string, 10);
  const sequenceId = parseInt(formData.get("sequenceId") as string, 10);
  const returnTo = (formData.get("returnTo") as string | null)?.trim() || "/";
  // Set inside the transaction ONLY when the bounded EOF normalization
  // (SEQGEN.SPLIT.WORKSPACE.1-FIX1, Lot B) actually commits — used after
  // the transaction to honestly clean up the now-orphaned old thumbnail
  // file. Never touched if validation fails or normalization didn't apply.
  // Two plain primitives (rather than one nullable object) to sidestep a
  // TS control-flow narrowing quirk observed with an object-typed `let`
  // reassigned only from inside the `db.transaction` closure.
  let normalizedOldThumbnailPath: string | null = null;
  let didNormalize = false;
  let warning: string | undefined;

  try {
    // Every decisive read (run status, live Shots, live segments) AND the
    // full diagnostics computation AND the status transition itself all
    // happen inside ONE synchronous transaction (no `await` anywhere in
    // this callback — better-sqlite3 requires that for `db.transaction` to
    // actually serialize against concurrent writers). This closes a real
    // race: an earlier version read the run/Shots/segments OUTSIDE the
    // transaction and only re-checked `status` inside it, so a Skip/
    // Reassign/Split committed between the read and the status-transition
    // could leave a `validated` plan that was never actually re-diagnosed
    // against what just changed. Now, whichever transaction — this
    // validation, or a concurrent edit — commits first is exactly what the
    // other one sees when it does its own fresh read, because SQLite
    // serializes writers.
    db.transaction((tx) => {
      const [fresh] = tx.select().from(sequenceVideoSplitRuns).where(eq(sequenceVideoSplitRuns.id, runId)).all() as unknown as (typeof sequenceVideoSplitRuns.$inferSelect)[];
      if (!fresh) throw new Error("Split run not found.");
      if (fresh.sequenceId !== sequenceId) throw new Error("Split run does not belong to this Sequence.");
      if (fresh.status !== "ready") throw new Error("This Split Plan was already validated or is no longer editable.");

      const sequenceShots = tx
        .select({ id: shots.id })
        .from(shots)
        .where(eq(shots.sequenceId, sequenceId))
        .orderBy(asc(shots.orderIndex))
        .all() as unknown as { id: number }[];
      const segments = tx
        .select()
        .from(sequenceVideoSplitSegments)
        .where(eq(sequenceVideoSplitSegments.splitRunId, runId))
        .orderBy(asc(sequenceVideoSplitSegments.orderIndex))
        .all() as unknown as (typeof sequenceVideoSplitSegments.$inferSelect)[];

      const diagnostics: string[] = [];

      // Staleness: the Sequence's Shot list/order must be exactly what this
      // run was created against.
      const liveOrderSnapshot = JSON.stringify(sequenceShots.map((s) => s.id));
      if (liveOrderSnapshot !== fresh.expectedShotOrderSnapshot) {
        diagnostics.push(
          "The Sequence's Shot list or order has changed since this Split Plan was detected. Run detection again to get an up-to-date plan."
        );
      }

      // Boundary validity: strictly increasing, contiguous, within [0, duration].
      const sorted = [...segments].sort((a, b) => a.orderIndex - b.orderIndex);

      // REVISE (SEQGEN.SPLIT.WORKSPACE.1-FIX1, Lot B) — bounded, one-shot
      // compatibility normalization for plans generated by the exact
      // legacy bug (EOF quantized to the nearest frame instead of kept as
      // the source's own high-precision duration). Diagnostics below run
      // against `effectiveSorted` — `sorted` with ONLY the last segment's
      // `endSeconds` replaced — so a plan is validated (and only then
      // persisted, atomically, in this same transaction) exactly as if the
      // fix had produced it originally. Applies ONLY when ALL of:
      //   1. the run is explicitly proven CFR (`frameRateMode === "cfr"`)
      //      with a numerically reliable `sourceFps` — never for VFR/
      //      unknown/legacy-unmarked runs, which get zero auto-repair;
      //   2. the last segment's CURRENT `endSeconds` matches, to strict
      //      floating-point epsilon, the EXACT legacy signature
      //      `roundBoundarySeconds(sourceDurationSeconds, sourceFps)` — an
      //      arbitrary/different endpoint (a real user edit, or a genuine
      //      gap) is NEVER touched;
      //   3. normalizing would still leave the last segment's own duration
      //      strictly positive.
      // If normalization doesn't apply, `effectiveSorted === sorted` and
      // behavior is byte-identical to before this fix.
      let normalizedLastSegmentCandidate: typeof sequenceVideoSplitSegments.$inferSelect | null = null;
      if (sorted.length > 0 && parseFrameRateModeFromParamsJson(fresh.paramsJson) === "cfr" && isReliableFps(fresh.sourceFps)) {
        const last = sorted[sorted.length - 1];
        const legacySignature = roundBoundarySeconds(fresh.sourceDurationSeconds, fresh.sourceFps);
        const EPSILON = 1e-9;
        // REVISE (Codex, SEQGEN.SPLIT.WORKSPACE.1-FIX1) — when the source
        // duration is itself already frame-aligned, the legacy signature
        // equals the exact EOF: matching the signature alone is not enough
        // to prove this run is actually broken. Require a REAL gap between
        // the current endpoint and the exact source duration before ever
        // selecting the normalization candidate — an already-exact plan
        // must never be touched (no rewrite, no thumbnail invalidation).
        if (
          Math.abs(last.endSeconds - legacySignature) < EPSILON &&
          Math.abs(last.endSeconds - fresh.sourceDurationSeconds) > EPSILON &&
          fresh.sourceDurationSeconds - last.startSeconds > 0
        ) {
          normalizedLastSegmentCandidate = last;
        }
      }
      const effectiveSorted = normalizedLastSegmentCandidate
        ? sorted.map((s, i) => (i === sorted.length - 1 ? { ...s, endSeconds: fresh.sourceDurationSeconds } : s))
        : sorted;

      if (effectiveSorted.length === 0) {
        diagnostics.push("This Split Plan has no segments.");
      } else {
        if (effectiveSorted[0].startSeconds !== 0) diagnostics.push("The first segment does not start at 0.");
        if (Math.abs(effectiveSorted[effectiveSorted.length - 1].endSeconds - fresh.sourceDurationSeconds) > 0.01) {
          diagnostics.push("The last segment does not end at the source video's duration.");
        }
        for (let i = 0; i < effectiveSorted.length; i++) {
          const s = effectiveSorted[i];
          if (s.endSeconds <= s.startSeconds) diagnostics.push(`Segment #${i + 1} has a zero or negative duration.`);
          if (i > 0 && Math.abs(effectiveSorted[i - 1].endSeconds - s.startSeconds) > 0.01) {
            diagnostics.push(`There is a gap or overlap between segment #${i} and segment #${i + 1}.`);
          }
        }
      }

      // Mapping completeness: every current Shot mapped exactly once among
      // non-skipped segments; every active segment has a Shot; no duplicate
      // target.
      const active = effectiveSorted.filter((s) => s.status !== "skipped");
      const unmappedActive = active.filter((s) => s.targetShotId === null);
      if (unmappedActive.length > 0) {
        diagnostics.push(`${unmappedActive.length} active segment(s) have no target Shot assigned.`);
      }
      const targetCounts = new Map<number, number>();
      for (const s of active) {
        if (s.targetShotId === null) continue;
        targetCounts.set(s.targetShotId, (targetCounts.get(s.targetShotId) ?? 0) + 1);
      }
      const duplicated = [...targetCounts.entries()].filter(([, count]) => count > 1);
      if (duplicated.length > 0) {
        diagnostics.push(`${duplicated.length} Shot(s) are targeted by more than one active segment.`);
      }
      const mappedShotIds = new Set([...targetCounts.keys()]);
      const missingShots = sequenceShots.filter((s) => !mappedShotIds.has(s.id));
      if (missingShots.length > 0) {
        diagnostics.push(`${missingShots.length} of this Sequence's Shot(s) are not mapped to any segment.`);
      }

      if (diagnostics.length > 0) {
        // Throwing rolls back the transaction — nothing is written when
        // validation is refused, whether or not normalization was
        // attempted: a plan that's invalid even AFTER the compatibility
        // view is applied is left completely untouched.
        throw new Error(diagnostics.join(" "));
      }

      // All diagnostics passed on the (possibly normalized) view — write
      // the normalization itself (if any) and the `validated` transition
      // together, atomically, in this same transaction.
      if (normalizedLastSegmentCandidate) {
        // The last segment's thumbnail was rendered from its OLD (frame-
        // quantized) end boundary — now genuinely stale. Invalidate the
        // pointer to `null` in the SAME transaction (DB before filesystem,
        // same discipline as every other thumbnail-affecting mutation in
        // this ticket); the actual file is deleted AFTER commit, honestly,
        // never silently.
        tx.update(sequenceVideoSplitSegments)
          .set({ endSeconds: fresh.sourceDurationSeconds, thumbnailPath: null, updatedAt: new Date().toISOString() })
          .where(eq(sequenceVideoSplitSegments.id, normalizedLastSegmentCandidate.id))
          .run();
        didNormalize = true;
        normalizedOldThumbnailPath = normalizedLastSegmentCandidate.thumbnailPath;
      }

      tx.update(sequenceVideoSplitRuns)
        .set({ status: "validated", validatedAt: new Date().toISOString(), updatedAt: new Date().toISOString() })
        .where(eq(sequenceVideoSplitRuns.id, runId))
        .run();
    });

    // REVISE (Lot B) — the normalization committed above; now honestly
    // clean up the old (now provably orphaned) thumbnail file. Never
    // regenerates a NEW thumbnail here: the run is already `validated`
    // (immutable) by the time this runs, and this ticket explicitly
    // forbids regenerating a thumbnail post-validation.
    if (didNormalize && normalizedOldThumbnailPath) {
      const cleanup = await deleteSegmentThumbnail(normalizedOldThumbnailPath);
      if (!cleanup.ok) warning = cleanup.error;
    }
  } catch (e) {
    errRedirectTo(returnTo, "splitError", e instanceof Error ? e.message : "Failed to validate Split Plan.");
  }

  okRedirectTo(returnTo, "splitValidated", warning);
}
