import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { setupTempDb, type TempDb } from "./helpers/tempDb";

/**
 * `src/lib/llmWorkspace/actions/proposalCommit.ts` — the per-entry commit
 * adaptation B5 (`LLMW.PROPOSAL.COMPONENT.1`) declared. `tsc` already
 * proves each builder's return type matches `Parameters<typeof
 * ACTION_BINDINGS[K]>`; this file proves the *values* the seven builders
 * actually produce, on the particularities the ticket named explicitly:
 *
 *  - `assetBible.generate` carries `description`/`notes` through untouched
 *    (registry behaviour 3 — a blank field becomes `null`; `assetBible`
 *    only generates three of the five fields `updateAssetDetailsInline`
 *    replaces, so the other two must never be nulled by this adapter).
 *  - `preserveAssetBibleField` is actually applied: a generated field the
 *    user cleared falls back to its pre-generation value, not to blank.
 *  - the two `redirectOnly` hidden-field builders (`shotPrompt.assist`,
 *    `sequencePrompt.assist`) produce exactly the field names
 *    `updateShotPrompt`/`updateSequencePrompt` read off their `FormData` —
 *    verified against the actions' own source, not restated from memory.
 *
 * `proposalCommit.ts` imports `./bindings` for its `Parameters<typeof
 * ACTION_BINDINGS[K]>` types, which imports the seven action modules at
 * module scope (`@/db`-touching); per this directory's convention
 * (`tests/actions/registry.test.ts`, `bindings.test.ts`), it is imported
 * dynamically in `beforeAll`, after `setupTempDb()` has set `DB_PATH` — even
 * though none of the builders under test touch the database themselves.
 */

let ctx: TempDb;
let proposalCommit: typeof import("@/lib/llmWorkspace/actions/proposalCommit");

beforeAll(async () => {
  ctx = await setupTempDb();
  proposalCommit = await import("@/lib/llmWorkspace/actions/proposalCommit");
});

afterAll(() => ctx.cleanup());

describe("buildAssetBibleCommitArgs — assetBible.generate → updateAssetDetailsInline", () => {
  it("carries description and notes through untouched, not nulled", () => {
    const [args] = proposalCommit.buildAssetBibleCommitArgs({
      assetId: 1,
      projectId: 2,
      description: "Existing description",
      notes: "Existing notes",
      existingVisualIdentity: "Old visual identity",
      existingUsageRules: "Old usage rules",
      existingForbiddenVariations: "Old forbidden variations",
      visualIdentity: "New visual identity",
      usageRules: "New usage rules",
      forbiddenVariations: "New forbidden variations",
    });

    expect(args.description).toBe("Existing description");
    expect(args.notes).toBe("Existing notes");
  });

  it("maps a null description/notes to an empty string, never to a value that would null the column", () => {
    const [args] = proposalCommit.buildAssetBibleCommitArgs({
      assetId: 1,
      projectId: 2,
      description: null,
      notes: null,
      existingVisualIdentity: "Visual identity",
      existingUsageRules: "Usage rules",
      existingForbiddenVariations: "Forbidden variations",
      visualIdentity: "Visual identity",
      usageRules: "Usage rules",
      forbiddenVariations: "Forbidden variations",
    });

    // `updateAssetDetailsInline` nulls a field only when it receives "" — a
    // pre-existing null description/notes (never generated by this
    // operation) must still round-trip as "" here, not as some other
    // sentinel that would change behaviour.
    expect(args.description).toBe("");
    expect(args.notes).toBe("");
  });

  it("applies preserveAssetBibleField: a generated field the user cleared falls back to its pre-generation value", () => {
    const [args] = proposalCommit.buildAssetBibleCommitArgs({
      assetId: 1,
      projectId: 2,
      description: "d",
      notes: "n",
      existingVisualIdentity: "Kept visual identity",
      existingUsageRules: "Kept usage rules",
      existingForbiddenVariations: "Kept forbidden variations",
      // The user cleared all three textareas after generation.
      visualIdentity: "   ",
      usageRules: "",
      forbiddenVariations: "\n",
    });

    expect(args.visualIdentity).toBe("Kept visual identity");
    expect(args.usageRules).toBe("Kept usage rules");
    expect(args.forbiddenVariations).toBe("Kept forbidden variations");
  });

  it("keeps a non-blank edited field as the user's own value, not the pre-generation one", () => {
    const [args] = proposalCommit.buildAssetBibleCommitArgs({
      assetId: 1,
      projectId: 2,
      description: "d",
      notes: "n",
      existingVisualIdentity: "Old",
      existingUsageRules: "Old",
      existingForbiddenVariations: "Old",
      visualIdentity: "  Edited by user  ",
      usageRules: "Edited by user",
      forbiddenVariations: "Edited by user",
    });

    expect(args.visualIdentity).toBe("Edited by user");
  });

  it("passes assetId/projectId through unchanged", () => {
    const [args] = proposalCommit.buildAssetBibleCommitArgs({
      assetId: 42,
      projectId: 7,
      description: "d",
      notes: "n",
      existingVisualIdentity: "",
      existingUsageRules: "",
      existingForbiddenVariations: "",
      visualIdentity: "v",
      usageRules: "u",
      forbiddenVariations: "f",
    });

    expect(args.assetId).toBe(42);
    expect(args.projectId).toBe(7);
  });
});

describe("buildAssetDescriptionFieldCommitArgs — assetDescription.generate / assetNotes.generate → updateAssetDescriptionFieldInline", () => {
  it("targets the description field in replace mode with trimmed content", () => {
    const [args] = proposalCommit.buildAssetDescriptionFieldCommitArgs({
      assetId: 1,
      projectId: 2,
      field: "description",
      mode: "replace",
      content: "  A generated description.  ",
    });

    expect(args).toEqual({
      assetId: 1,
      projectId: 2,
      field: "description",
      mode: "replace",
      content: "A generated description.",
    });
  });

  it("targets the notes field in append mode", () => {
    const [args] = proposalCommit.buildAssetDescriptionFieldCommitArgs({
      assetId: 1,
      projectId: 2,
      field: "notes",
      mode: "append",
      content: "A generated note.",
    });

    expect(args.field).toBe("notes");
    expect(args.mode).toBe("append");
  });
});

describe("buildApplyGeneratedStoryArgs / buildApplyGeneratedOutlineArgs — positional commits", () => {
  it("returns [projectId, story] in that order for story.generate", () => {
    expect(proposalCommit.buildApplyGeneratedStoryArgs(9, "The story text")).toEqual([9, "The story text"]);
  });

  it("returns [projectId, outline] in that order for outline.generate", () => {
    expect(proposalCommit.buildApplyGeneratedOutlineArgs(9, "The outline text")).toEqual([9, "The outline text"]);
  });
});

describe("buildUpdateShotPromptHiddenFields — shotPrompt.assist → updateShotPrompt (redirectOnly)", () => {
  it("produces exactly the field names updateShotPrompt reads off its FormData (src/actions/shots.ts)", () => {
    const fields = proposalCommit.buildUpdateShotPromptHiddenFields({
      projectId: 1,
      sequenceId: 2,
      shotId: 3,
      shotPrompt: "A shot prompt",
      returnTo: "/projects/1/sequences/2/shots/3",
    });

    expect(Object.keys(fields).sort()).toEqual(
      ["projectId", "sequenceId", "shotId", "shotPrompt", "returnTo"].sort()
    );
    expect(fields.projectId).toBe("1");
    expect(fields.sequenceId).toBe("2");
    expect(fields.shotId).toBe("3");
    expect(fields.shotPrompt).toBe("A shot prompt");
    expect(fields.returnTo).toBe("/projects/1/sequences/2/shots/3");
  });
});

describe("buildUpdateSequencePromptHiddenFields — sequencePrompt.assist → updateSequencePrompt (redirectOnly)", () => {
  it("produces exactly the field names updateSequencePrompt reads off its FormData (src/actions/sequences.ts)", () => {
    const fields = proposalCommit.buildUpdateSequencePromptHiddenFields({
      projectId: 1,
      sequenceId: 2,
      sequencePrompt: "A sequence prompt",
      returnTo: "/projects/1/sequences/2",
    });

    expect(Object.keys(fields).sort()).toEqual(["projectId", "sequenceId", "sequencePrompt", "returnTo"].sort());
    expect(fields.projectId).toBe("1");
    expect(fields.sequenceId).toBe("2");
    expect(fields.sequencePrompt).toBe("A sequence prompt");
    expect(fields.returnTo).toBe("/projects/1/sequences/2");
  });
});
